- name: Build production environment
  gather_facts: no  
  hosts: localhost
  connection: local
  tasks:

    - name: upload production key pair
      local_action:
        module: rax_keypair
        credentials: "{{ credentials }}"
        name: production_key
        public_key: "{{ lookup('file', '/home/rack/.ssh/production_rsa.pub') }}"
        region: "{{ region }}"

    - name: Create load balancer
      local_action:
        module: rax_clb
        credentials: "{{ credentials }}"
        name: production
        port: "{{ lbport }}"
        protocol: "{{ lbproto }}"
        type: "{{ lbtype }}" 
        timeout: "{{ lbtimeout }}"
        region: "{{ region }}"
        wait: "{{ lbwait }}"
        state: present
        meta:
          app: "{{ domain }}" 
      register: clb

    - name: Get authentication token
      shell: curl -s https://identity.api.rackspacecloud.com/v2.0/tokens -X POST
             -d '{"auth":{"RAX-KSKEY:apiKeyCredentials":{"username":"{{ raxuser }}", "apiKey":"{{ raxkey }}"}}}'
             -H "Content-Type:application/json"
      register: raxauth

    - name: Enable SSL termination and add SSL certificate
      shell: curl -s -X PUT -H "X-Auth-Token:{{ (raxauth.stdout|from_json).access.token.id }}" -H "Content-Type:application/json" -d @"{{ ssljson }}"
             https://{{ region }}.loadbalancers.api.rackspacecloud.com/v1.0/{{ raxid }}/loadbalancers/{{ clb.balancer.id }}/ssltermination

    - pause: seconds=25

    - name: Enable HTTPS redirect on Load Balancer
      shell: curl -s -X PUT -H "X-Auth-Token:{{ (raxauth.stdout|from_json).access.token.id }}" -H "Content-Type:application/json" 
             -d '{"loadBalancer":{"name":"production", "protocol":"{{ lbproto }}", "httpsRedirect":true}}'
             https://{{ region }}.loadbalancers.api.rackspacecloud.com/v1.0/{{ raxid }}/loadbalancers/{{ clb.balancer.id }}

    - name: Create cloud servers
      local_action:
        module: rax
        credentials: "{{ credentials }}"
        key_name: production_key
        name: web%02d.mywebsiteinthecloud.com
        flavor: "{{ csflavor }}" 
        image: "{{ csimage }}" 
        networks:
          - public
          - private
        region: "{{ region }}"
        state: present
        count: 2
        exact_count: yes
        group: production 
        wait: yes
      register: prod

    - name: Add servers to web host group
      local_action:
        module: add_host
        hostname: "{{ item.name }}"
        ansible_host: "{{ item.rax_accessipv4 }}"
        groups: production
      with_items: prod.success

    - name: Add nodes to production load balancer
      local_action:
        module: rax_clb_nodes
        load_balancer_id: "{{ clb.balancer.id }}" 
        address: "{{ item.rax_networks.private|first }}" 
        port: "{{ nodeport }}"
        condition: "{{ nodecondition }}"
        type: "{{ nodetype }}"
        wait: yes
        credentials: "{{ credentials }}"
        region: "{{ region }}"
      with_items: prod.success

    - name: Add DNS records for production servers
      local_action:
        module: rax_dns_record
        credentials: "{{ credentials }}"
        domain: "{{ domain }}" 
        name: "{{ item.name }}"
        data: "{{ item.rax_accessipv4 }}"
        type: A
        ttl: "{{ dnsttl }}"
      with_items: prod.success

    - name: Add DNS record for production environment
      local_action:
        module: rax_dns_record
        credentials: "{{ credentials }}"
        domain: "{{ domain }}" 
        name: "{{ domain }}" 
        data: "{{ clb.balancer.virtual_ips[0].address }}"
        type: A
        ttl: "{{ dnsttl }}"

    - name: Add DNS record for production environment
      local_action:
        module: rax_dns_record
        credentials: "{{ credentials }}"
        domain: "{{ domain }}" 
        name: www.mywebsiteinthecloud.com
        data: "{{ domain }}" 
        type: CNAME
        ttl: "{{ dnsttl }}"

