- name: Build staging environment
  gather_facts: no  
  hosts: localhost
  connection: local
  tasks:

    - name: upload staging key pair
      local_action:
        module: rax_keypair
        credentials: "{{ credentials }}"
        name: staging_key
        public_key: "{{ lookup('file', '/home/rack/.ssh/staging_rsa.pub') }}"
        region: "{{ region }}"

    - name: Create load balancer
      local_action:
        module: rax_clb
        credentials: "{{ credentials }}"
        name: staging
        port: "{{ lbport }}"
        protocol: "{{ lbproto }}"
        type: "{{ lbtype }}" 
        timeout: "{{ lbtimeout }}"
        region: "{{ region }}"
        wait: "{{ lbwait }}"
        state: present
        meta:
          app: "{{ domain }}" 
      register: clb

    - name: Create cloud servers
      local_action:
        module: rax
        credentials: "{{ credentials }}"
        key_name: staging_key
        name: stag%02d.mywebsiteinthecloud.com
        flavor: "{{ csflavor }}" 
        image: "{{ csimage }}" 
        networks:
          - public
          - private
        region: "{{ region }}"
        state: present
        count: 2
        exact_count: yes
        group: staging 
        wait: yes
      register: stag

    - name: Add servers to web host group
      local_action:
        module: add_host
        hostname: "{{ item.name }}"
        ansible_host: "{{ item.rax_accessipv4 }}"
        groups: staging
      with_items: stag.success

    - name: Add nodes to staging load balancer
      local_action:
        module: rax_clb_nodes
        load_balancer_id: "{{ clb.balancer.id }}" 
        address: "{{ item.rax_networks.private|first }}" 
        port: "{{ nodeport }}"
        condition: "{{ nodecondition }}"
        type: "{{ nodetype }}"
        wait: yes
        credentials: "{{ credentials }}"
        region: "{{ region }}"
      with_items: stag.success

    - name: Add DNS records for staging servers
      local_action:
        module: rax_dns_record
        credentials: "{{ credentials }}"
        domain: "{{ domain }}" 
        name: "{{ item.name }}"
        data: "{{ item.rax_accessipv4 }}"
        type: A
        ttl: "{{ dnsttl }}"
      with_items: stag.success

    - name: Add DNS record for staging environment
      local_action:
        module: rax_dns_record
        credentials: "{{ credentials }}"
        domain: "{{ domain }}" 
        name: staging.mywebsiteinthecloud.com
        data: "{{ clb.balancer.virtual_ips[0].address }}"
        type: A
        ttl: "{{ dnsttl }}"

